name: Preview

on:
  pull_request:

env:
  NEXT_PUBLIC_GA_ID: ${{secrets.NEXT_PUBLIC_GA_ID}}

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Add any build steps here. For example:
      - run: yarn && yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          # default expire value 7 days
          projectId: fts-month-stg
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
